#!/bin/bash
#
# Run the PDX CTP nextflow pipeline 
#
# Example:  ./run_ctp  TM00099  BR1367F003P6  --real
#
# This script takes care of submitting a slurm job using sbatch.
# When SA team releases a new pipeline version, CS-Ops updates VERSION here.
#
# If --real  is specified, it's a real production run and the result folder 
# will be named so that the db loader will load from it next time it runs.
#
# For command line options see the Usage statement and case statements below.
#

VERSION="1.0.0"
NF_SCRIPT=pipelines/Exome/$VERSION/hctp_en_mutect.nf
PDX=/pdx/pdx_resource_service/elion
CMD=run_ctp


# get mandatory first three command line args...
if [ $# -lt 2 ]; then
    echo "Usage: $CMD  modelname  samplename  [options]"
    echo "Quitting."
    exit 1
fi
MODEL=$1
SAMPLE=$2
PLATFORM=CTP


# get any additional command line --options...  first set the defaults...
real=no                  # if --real it's a real production run
all_but_launch=no        # if --all_but_launch  do prelimaries but stop short of pipeline launch
preserve_work=no         # if --preserve_work  don't delete nextflow's ./work dir at end
resultloc="default"      # specify to put result folder somewhere other than ./analysis
indir="default"          # specify to set a special dir to get fastq files from
min_pct_hq_reads=50      # minimum % high quality reads
email="stephen.grubb@jax.org"

shift 2
for iarg in "$@"
do
  case $iarg in
    --preserve_work)
      preserve_work=yes
      shift
      ;;
    --real)
      real=yes
      shift
      ;;
    --all_but_launch)
      all_but_launch=yes
      real=no
      shift
      ;;
    --email=*)
      email="${iarg#*=}"
      shift
      ;;
    --min_pct_hq_reads=*)
      min_pct_hq_reads="${iarg#*=}"
      shift
      ;;
    --resultloc=*)
      resultloc="${iarg#*=}"
      shift
      ;;
    --indir=*)
      indir="${iarg#*=}"
      shift
      ;;
    CTP)
      # placeholder arg does nothing
      shift
      ;;
    *)
      echo "ERROR: $CMD quitting: unrecognized arg: ${iarg}"
      exit 1
      ;;
  esac
done


if [ $real == "yes" ]; then 
  GROUP=`id -gn`
  if [ "$USER" != "svc-pdx" -o $GROUP != "pdx-data" ]; then
    echo "ERROR: you must be svc-pdx (group pdx-data) to do --real"
    exit 1
  fi
fi


# determine where the fastq files are and do sanity checks...
if [ $indir == "default" ]; then
  indir=$PDX/seqdata/$MODEL/$SAMPLE/CTP
fi
if [ -d $indir ]; then
  test
else
  echo "ERROR: $CMD quitting: fastq dir doesn't exist: $indir"
  exit 1
fi
nfastq=`(cd $indir; ls *.fastq.gz) | wc -l`
if [ $nfastq -lt 2 ]; then
  echo "ERROR: $CMD quitting: 2+ fastq files not seen: $indir"
  exit 1
fi


# go to the general result location...
if [ $resultloc == "default" ]; then
  cd $PDX/analysis/$MODEL
else
  cd $resultloc
fi
if [ $? -ne 0 ]; then
  echo "ERROR: $CMD quitting: cannot chdir to $resultloc result location (model=$MODEL)"
  exit 1
fi


# build result folder name, derived from fastq name... and cd into it
outdir=`(cd $indir; ls *.fastq.gz) | head -1 | sed "s/_R[1-9]_.*$//" `
if [ $real != "yes" -a $resultloc == "default" ]; then
  outdir="test_run_$outdir"
fi
if [ -d $outdir ]; then
  echo -n "ERROR: $CMD quitting: result folder already exists ($outdir). "
  show_folder_status $outdir
  exit 1
fi

mkdir $outdir
cd $outdir

if [ $? -ne 0 ]; then
  echo "ERROR: $CMD quitting: cannot chdir to $outdir"
  exit 1
fi


# create a status file with version info...
echo "$PLATFORM  $VERSION  $NF_SCRIPT" > pipeline_running.txt



# list the fastq files, prepend each with the string "${FQ_PATH}/" (a variable used 
# within config file), and end up with a comma-separated list...
FASTQS_LIST=`(cd $indir; ls *.fastq.gz)| sed 's/^/${FQ_PATH}\//' | paste -s -d, - `


# build the params.config file...
echo "// params.config : `date`

params
{
    FQ_PATH=\"$indir\"                    
    fastqInputs = \"$FASTQS_LIST\"
    min_pct_hq_reads = \"$min_pct_hq_reads\"
    preserve_work = \"$preserve_work\"
}"                                > params.config


if [ $all_but_launch != "no" ]; then
  echo "At user request, stopping just short of launching the pipeline..."
  exit 1
fi

jobname="pdx_${PLATFORM}_${MODEL}_${SAMPLE}"

# launch the pipeline........   
sbatch  --job-name=$jobname  \
  --mail-user=$email  --mail-type=END \
  -q batch   -t 72:00:00  --mem=2000  \
  nextflow -c ./params.config   run $PDX/$NF_SCRIPT   -profile slurm,singularity   -with-dag nf_reports/flowchart.pdf

